### ISSUE TITLE
Error inflating BarcodeCameraView

### ISSUE THREAD

**Issue by dottorp** [doo/scanbot-sdk-example-xamarin#4]
I'm trying to scan a QR Code in the Android app by using the same code in the sample. When starting the activity with StartActivityForResult the app crashes with the following error:

Unhandled Exception:
Java.Lang.RuntimeException: Unable to start activity ComponentInfo{my.app/io.scanbot.sdk.ui.view.barcode.BarcodeScannerActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class io.scanbot.sdk.ui.view.barcode.BarcodeCameraView

I've already updated the Nuget package to the latest version, and double-checked project's properties to ensure I'm using the same API levels.

**Comment by dottorp** [comment]
Solved by myself deleting cache & data.

**Comment by eddyfrank** [comment]
OK, glad to hear you solved the issue.

Anyway, for further issues please check and provide the entire exception stacktrace. You can see the actual cause for an `InflateException` at the end of the stacktrace. 
(E.g. a typical cause for an `InflateException` with Scanbot CameraViews is when the Scanbot SDK was not initialized.)

**Comment by dottorp** [comment]
Scanbot was initialized all times.
